name=Step_Runner
version=1.0.1
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library untuk menjalankan fungsi periodik tanpa delay().
paragraph=Step_Runner membantu membuat sistem multitasking sederhana di Arduino dengan prinsip non-blocking timing berbasis millis().
category=Timing
url=https://github.com/0ADILL3/Step_Runner
architectures=*
includes=Step_Runner.h