name=Step_Runner
version=1.1.1
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=Library ringan untuk menjalankan fungsi periodik (Blink), ON-Delay, dan OFF-Delay tanpa memblokir sistem.
paragraph=Step_Runner membantu membuat sistem multitasking sederhana di Arduino dengan prinsip non-blocking timing berbasis millis(). Kini mendukung eksekusi periodik, penundaan eksekusi (One-Shot/ON-Delay), dan timer durasi (Pulse/OFF-Delay) dengan manajemen memori yang sangat hemat.
category=Timing
url=https://github.com/0ADILL3/Step_Runner
architectures=*
includes=Step_Runner.h